/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PractitionersRouteImport } from './routes/practitioners'
import { Route as FieldRouteImport } from './routes/field'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FieldSitesSiteIdRouteImport } from './routes/field.sites.$siteId'

const PractitionersRoute = PractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldSitesSiteIdRoute = FieldSitesSiteIdRouteImport.update({
  id: '/sites/$siteId',
  path: '/sites/$siteId',
  getParentRoute: () => FieldRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/field': typeof FieldRouteWithChildren
  '/practitioners': typeof PractitionersRoute
  '/field/sites/$siteId': typeof FieldSitesSiteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/field': typeof FieldRouteWithChildren
  '/practitioners': typeof PractitionersRoute
  '/field/sites/$siteId': typeof FieldSitesSiteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/field': typeof FieldRouteWithChildren
  '/practitioners': typeof PractitionersRoute
  '/field/sites/$siteId': typeof FieldSitesSiteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/field' | '/practitioners' | '/field/sites/$siteId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/field' | '/practitioners' | '/field/sites/$siteId'
  id: '__root__' | '/' | '/field' | '/practitioners' | '/field/sites/$siteId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FieldRoute: typeof FieldRouteWithChildren
  PractitionersRoute: typeof PractitionersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practitioners': {
      id: '/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof PractitionersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/sites/$siteId': {
      id: '/field/sites/$siteId'
      path: '/sites/$siteId'
      fullPath: '/field/sites/$siteId'
      preLoaderRoute: typeof FieldSitesSiteIdRouteImport
      parentRoute: typeof FieldRoute
    }
  }
}

interface FieldRouteChildren {
  FieldSitesSiteIdRoute: typeof FieldSitesSiteIdRoute
}

const FieldRouteChildren: FieldRouteChildren = {
  FieldSitesSiteIdRoute: FieldSitesSiteIdRoute,
}

const FieldRouteWithChildren = FieldRoute._addFileChildren(FieldRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FieldRoute: FieldRouteWithChildren,
  PractitionersRoute: PractitionersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
