/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PractitionersRouteImport } from './routes/practitioners'
import { Route as IndexRouteImport } from './routes/index'

const PractitionersRoute = PractitionersRouteImport.update({
  id: '/practitioners',
  path: '/practitioners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practitioners': typeof PractitionersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practitioners': typeof PractitionersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practitioners': typeof PractitionersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/practitioners'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/practitioners'
  id: '__root__' | '/' | '/practitioners'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PractitionersRoute: typeof PractitionersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/practitioners': {
      id: '/practitioners'
      path: '/practitioners'
      fullPath: '/practitioners'
      preLoaderRoute: typeof PractitionersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PractitionersRoute: PractitionersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
